Header
onedebos/newsweek-clone pull request #1
Opened 2019-07-25 22:51 UTC by onedebos

2019-07-26 12:23 UTC, mosaaleb commented
Reviewing.

2019-07-26 19:01 UTC, mosaaleb commented on index.html
> +                            <a href="#" class="feature-hover"> To Our Readers:</a>
Top story section is wrapped with `<section>` tag and its story inside has `<article>` tag for more semantic tags.

2019-07-26 19:02 UTC, mosaaleb commented on index.html
> +                                <div>
Same idea for more stories section, wrapped around `<section>` and each story has `<article>` tag.

2019-07-26 19:05 UTC, mosaaleb commented on index.html
> +                <section class="col-xl-4 col-lg-4 col-md-5 col-sm-12 mt-4 order-sm-second order-md-first pl-lg-4">
featured stories section is wrapped around `<section>`, and each story inside it has `<article>` tag.

2019-07-26 19:09 UTC, mosaaleb commented on index.html
> +                                </p>
OPINION section wrapped by `<section>` tags, and each opinion has `<article>` tag around

2019-07-26 19:11 UTC, mosaaleb commented on index.html
> +                        <a href="#">
LATEST NEWS is wrapped by `<section>`, and each article has `<article>` tag around.

2019-07-26 19:15 UTC, mosaaleb commented on index.html
> +                                    Trouble</a>
IN THE MAGAZINE section is wrapped around `<section>`, and each magazine has `<article>` tag around it.

2019-07-26 19:16 UTC, mosaaleb commented on index.html
> +                            <span class="mg-section ">
The same semantic tags `<section>` and `<article>` apply to EDITOR PICKS section.

2019-07-26 19:17 UTC, mosaaleb commented on index.html
> +                        <div>
The same concent of semantic tags `<section>` and `<article>` also applies in FEATURED SLIDESHOWS section.

2019-07-26 19:24 UTC, mosaaleb commented on index.html
> +                </div>
The top part and the botom part of footer need to inside `<footer>` tag

2019-07-26 19:40 UTC, mosaaleb requested changes
## Hi @onedebos 

### Impressive work :clap:. We still have some minor requirements most of them are related to the use of semantic tags.



### Mobile Screen
#### Nav bar

- [ ] (Mobile screen) has sign in and subscribe button -- as seen on newsweek.
- [ ] The SUBSCRIBE section is kind of messed up in mobile screen and overlapping text with the image. Let's fix it.
![subscribe](https://user-images.githubusercontent.com/4246637/61976208-6b119300-afeb-11e9-8e9b-e728d5fe61ec.png)

### Medium Screen

- [ ] The SUBSCRIBE  SECTION is also messed up in the medium screen. Causing the whole page to be very wide.
![Screenshot from 2019-07-26 21-30-36](https://user-images.githubusercontent.com/4246637/61976666-ab254580-afec-11e9-8db2-722d5fc54749.png)


### Large Screen

- [ ] Also the same problem with SUBSCRIBE and NEWSLETTER section
- [ ] Also there is overalapping between logo and newsweek text in the footer.
![Screenshot from 2019-07-26 21-36-02](https://user-images.githubusercontent.com/4246637/61977217-23d8d180-afee-11e9-9360-63b136b515ca.png)

Please submit a new code review once you have finished with these requirements. 


Contact me on slack if you have any questions.
### Happy coding :computer:

2019-07-28 21:57 UTC, bolah2009 commented
PR currently under review

2019-07-28 23:45 UTC, bolah2009 approved these changes
## Nice Job [Adebola](../../) :clap: :1st_place_medal: 

The [clone](https://raw.githack.com/onedebos/newsweek-clone/header/index.html) looks good to me and is responsive. :+1: 


#### Check out the comment below and [these errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fonedebos%2Fnewsweek-clone%2Fheader%2Findex.html) on using an heading (h1-h6) element in an `<article>` and `<section>` elelment. Consider checking them out before merging.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-07-28 23:45 UTC, bolah2009 commented on styles.css
> +
Consider deleting commented out code.

2019-07-29 10:27 UTC, merged